use matrix_sdk::encryption::verification::{
    SasState, SasVerification, VerificationRequest, VerificationRequestState,
};
use matrix_sdk::ruma::OwnedUserId;
use std::sync::Arc;

use super::state::{CrossSigningInfo, DeviceInfo, Threepid};

#[derive(Debug, Clone)]
pub enum Message {
    LoadProfile,
    LoadIgnoredUsers,
    IgnoredUsersLoaded(Result<Vec<OwnedUserId>, String>),
    NewIgnoreUserIdChanged(String),
    IgnoreUser,
    UserIgnored(Result<(), String>),
    UnignoreUser(OwnedUserId),
    UserUnignored(OwnedUserId, Result<(), String>),
    ProfileLoaded(Result<Option<String>, String>),
    AvatarUrlLoaded(Result<Option<String>, String>),
    AvatarMediaFetched(Result<Vec<u8>, String>),
    SelectAvatar,
    AvatarFileSelected(Option<std::path::PathBuf>),
    AvatarUploaded(Result<String, String>),
    DisplayNameChanged(String),
    SaveProfile,
    ProfileSaved(Result<(), String>),
    DismissError,
    CurrentPasswordChanged(String),
    NewPasswordChanged(String),
    ConfirmNewPasswordChanged(String),
    ChangePassword,
    PasswordChanged(Result<(), String>),
    DismissPasswordSuccess,
    LoadDevices,
    DevicesLoaded(Result<Vec<DeviceInfo>, String>),
    VerifyDevice(Arc<str>),
    VerificationRequested(Result<VerificationRequest, String>),
    VerificationRequestStateChanged(VerificationRequestState),
    SasStarted(Result<Option<SasVerification>, String>),
    SasStateChanged(SasState),
    ConfirmEmojis,
    EmojisConfirmed(Result<(), String>),
    CancelVerification,
    DeviceDeletePasswordChanged(String),
    StartRenameDevice(Arc<str>),
    CancelRenameDevice(Arc<str>),
    EditDeviceNameChanged(Arc<str>, String),
    SaveDeviceName(Arc<str>),
    DeviceRenamed(Arc<str>, Result<(), String>),
    DeleteDevice(Arc<str>),
    DeviceDeleted(Arc<str>, Result<(), String>),
    DeactivatePasswordChanged(String),
    DeactivateAccount,
    AccountDeactivated(Result<(), String>),
    GlobalNotificationModeChanged(
        bool,
        matrix_sdk::notification_settings::RoomNotificationMode,
    ),
    GlobalNotificationModeLoaded(
        bool,
        matrix_sdk::notification_settings::RoomNotificationMode,
    ),
    GlobalNotificationModeSet(Result<(), String>),
    LoadCrossSigningStatus,
    CrossSigningStatusLoaded(Result<Option<CrossSigningInfo>, String>),
    BootstrapCrossSigning,
    CrossSigningBootstrapped(Result<(), String>),
    ToggleMediaPreviewsDisplayPolicy(bool),
    ToggleInviteAvatarsDisplayPolicy(bool),
    Load3PIDs,
    ThreepidsLoaded(Result<Vec<Threepid>, String>),
    New3PIDEmailChanged(String),
    New3PIDMsisdnChanged(String),
    New3PIDCountryCodeChanged(String),
    Request3PIDEmailToken,
    Request3PIDMsisdnToken,
    ThreepidTokenRequested(Result<String, String>),
    Add3PIDPasswordChanged(String),
    Add3PID,
    ThreepidAdded(Result<(), String>),
    Delete3PID(String, matrix_sdk::ruma::thirdparty::Medium),
    ThreepidDeleted(String, Result<(), String>),
    DismissSuccessMessage,
    LoadKeywords,
    KeywordsLoaded(Vec<String>),
    NewKeywordChanged(String),
    AddKeyword,
    KeywordAdded(Result<(), String>),
    RemoveKeyword(String),
    KeywordRemoved(Result<(), String>),
    IgnoreUserById(matrix_sdk::ruma::OwnedUserId),
    UnignoreUserById(matrix_sdk::ruma::OwnedUserId),
}
