use matrix_sdk::ruma::events::room::history_visibility::HistoryVisibility;
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub enum Message {
    LoadRoom(std::sync::Arc<str>),
    RoomLoaded(Box<Result<RoomInfo, String>>),
    NameChanged(String),
    TopicChanged(String),
    SaveRoom,
    RoomSaved(Result<(), String>),
    DismissError,
    AvatarMediaFetched(Result<Vec<u8>, String>),
    SelectAvatar,
    AvatarFileSelected(Option<std::path::PathBuf>),
    AvatarUploaded(Result<(), String>),
    LeaveRoom,
    RoomLeft(Result<(), String>),
    ForgetRoom,
    RoomForgotten(Result<(), String>),
    LoadPowerLevels,
    PowerLevelsLoaded(Result<PowerLevelInfo, String>),
    PendingPowerLevel(String, i64),
    CommitPowerLevel(String),
    PowerLevelUpdated(String, Result<(), String>),
    BanLevelChanged(String),
    InviteLevelChanged(String),
    KickLevelChanged(String),
    RedactLevelChanged(String),
    EventsDefaultLevelChanged(String),
    RoomNameLevelChanged(String),
    RoomTopicLevelChanged(String),
    RoomAvatarLevelChanged(String),
    InviteUser,
    UserInvited(Result<(), String>),
    KickUser(String),
    UserKicked(String, Result<(), String>),
    BanUser(String),
    UserBanned(String, Result<(), String>),
    InviteUserIdChanged(String),
    ActionReasonChanged(String),
    MemberFilterChanged(String),
    NotificationModeChanged(matrix_sdk::notification_settings::RoomNotificationMode),
    NotificationModeSet(Result<(), String>),
    JoinRuleChanged(matrix_sdk::ruma::events::room::join_rules::JoinRule),
    HistoryVisibilityChanged(HistoryVisibility),
    RestrictedSpaceIdChanged(String),
    IgnoreUser(matrix_sdk::ruma::OwnedUserId),
    UnignoreUser(matrix_sdk::ruma::OwnedUserId),
    EnableEncryption,
    EncryptionEnabled(Result<(), String>),
    CanonicalAliasChanged(String),
    AltAliasAdded,
    AltAliasRemoved(String),
    NewAltAliasInputChanged(String),
}

#[derive(Debug, Clone)]
pub struct PowerLevelInfo {
    pub default_level: i64,
    pub users: HashMap<matrix_sdk::ruma::OwnedUserId, i64>,
    pub my_level: i64,
}

#[derive(Debug, Clone)]
pub struct RoomInfo {
    pub name: String,
    pub topic: String,
    pub avatar_url: Option<String>,
    pub membership: matrix_sdk::RoomState,
    pub ban_level: i64,
    pub invite_level: i64,
    pub kick_level: i64,
    pub redact_level: i64,
    pub events_default_level: i64,
    pub room_name_level: i64,
    pub room_topic_level: i64,
    pub room_avatar_level: i64,
    pub current_user_id: Option<String>,
    pub notification_mode: Option<matrix_sdk::notification_settings::RoomNotificationMode>,
    pub join_rule: Option<matrix_sdk::ruma::events::room::join_rules::JoinRule>,
    pub history_visibility: Option<HistoryVisibility>,
    pub ignored_users: Vec<matrix_sdk::ruma::OwnedUserId>,
    pub is_encrypted: bool,
    pub canonical_alias: Option<String>,
    pub alt_aliases: Vec<String>,
}
