use matrix_sdk::ruma::events::room::history_visibility::HistoryVisibility;
use std::collections::HashMap;
use std::sync::Arc;

#[derive(Debug, Clone, Default)]
pub struct State {
    pub room_id: Option<Arc<str>>,
    pub name: String,
    pub original_name: String,
    pub topic: String,
    pub original_topic: String,
    pub is_loading: bool,
    pub is_saving: bool,
    pub error: Option<String>,
    pub avatar_url: Option<String>,
    pub avatar_handle: Option<cosmic::iced::widget::image::Handle>,
    pub is_uploading_avatar: bool,
    pub is_loading_avatar: bool,
    pub membership: Option<matrix_sdk::RoomState>,
    pub power_levels: Option<(i64, HashMap<matrix_sdk::ruma::OwnedUserId, i64>)>,
    pub is_loading_power_levels: bool,
    pub updating_power_level_for: Option<String>,
    pub pending_power_level: Option<(String, i64)>,
    pub ban_level: i64,
    pub original_ban_level: i64,
    pub invite_level: i64,
    pub original_invite_level: i64,
    pub kick_level: i64,
    pub original_kick_level: i64,
    pub redact_level: i64,
    pub original_redact_level: i64,
    pub events_default_level: i64,
    pub original_events_default_level: i64,
    pub room_name_level: i64,
    pub original_room_name_level: i64,
    pub room_topic_level: i64,
    pub original_room_topic_level: i64,
    pub room_avatar_level: i64,
    pub original_room_avatar_level: i64,
    pub invite_level_str: String,
    pub kick_level_str: String,
    pub ban_level_str: String,
    pub redact_level_str: String,
    pub events_default_level_str: String,
    pub room_name_level_str: String,
    pub room_topic_level_str: String,
    pub room_avatar_level_str: String,
    pub invite_user_id: String,
    pub kick_user_id: String,
    pub ban_user_id: String,
    pub action_reason: String,
    pub current_user_id: Option<String>,
    pub my_power_level: i64,
    pub member_filter: String,
    pub notification_mode: Option<matrix_sdk::notification_settings::RoomNotificationMode>,
    pub is_loading_notifications: bool,
    pub join_rule: Option<matrix_sdk::ruma::events::room::join_rules::JoinRule>,
    pub history_visibility: Option<HistoryVisibility>,
    pub restricted_space_id: String,
    pub ignored_users: Vec<matrix_sdk::ruma::OwnedUserId>,
    pub is_encrypted: bool,
    pub canonical_alias: String,
    pub original_canonical_alias: String,
    pub alt_aliases: Vec<String>,
    pub original_alt_aliases: Vec<String>,
    pub new_alt_alias_input: String,
}
